server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据库操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver   # 当前sql驱动包
    url: jdbc:mysql://localhost:3306/db-cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 20101216

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ann.springcloud.entities  # 所有entity别名类所在包