server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      # 在此处配置要绑定的rabbitmq的服务信息
      binders:
        # 表示定义的名称，用于binding整合
        defaultRabbit:
          #  消息组件类型
          type: rabbit
          # 设置rabbitmq的相关的环境配置
          enviroment:
            spring:
              rabbitmq:
                host: localhost
                port: 15672
                username: guest
                password: guest
      # 服务的整合处理
      bindings:
        # 这个名字是一个通道名称
        input:
          # 表示使用exchange名称定义
          destination: studyzExchange
          # 设置消息类型，本次为json；文本则设置"text/plain"
          content-type: application/json
          # 设置要绑定的消息服务的具体设置
          binder: defaultRabbit
          # 分组
          #group: longquanA


eureka:
  client:
    # 表示是否将自己注册到EurekaServer 默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取自己的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 单机版
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过来5秒的间隔（默认是90秒）
    instance-id: receive-8802.com # 在消息列表时显示主机名称
    prefer-ip-address: true # 访问的路径变为IP地址